/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CommunityLevel = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'creator' : IDL.Principal,
  'ratings' : IDL.Vec(IDL.Nat),
  'playCount' : IDL.Nat,
  'tileData' : IDL.Text,
  'averageRating' : IDL.Float64,
});
export const PlayerProfile = IDL.Record({
  'username' : IDL.Text,
  'bestScoresPerLevel' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat)),
  'unlockedLevels' : IDL.Vec(IDL.Nat),
});
export const Time = IDL.Int;
export const LeaderboardEntry = IDL.Record({
  'player' : IDL.Principal,
  'score' : IDL.Nat,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteLevel' : IDL.Func([IDL.Nat], [], []),
  'getAllCommunityLevels' : IDL.Func([], [IDL.Vec(CommunityLevel)], ['query']),
  'getAllLevels' : IDL.Func([], [IDL.Vec(CommunityLevel)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(PlayerProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCommunityLevel' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(CommunityLevel)],
      ['query'],
    ),
  'getLeaderboardEntries' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(LeaderboardEntry)],
      ['query'],
    ),
  'getTopRatedLevels' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(CommunityLevel)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(PlayerProfile)],
      ['query'],
    ),
  'incrementPlayCount' : IDL.Func([IDL.Nat], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'publishLevel' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'rateLevel' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([PlayerProfile], [], []),
  'submitScore' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CommunityLevel = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'creator' : IDL.Principal,
    'ratings' : IDL.Vec(IDL.Nat),
    'playCount' : IDL.Nat,
    'tileData' : IDL.Text,
    'averageRating' : IDL.Float64,
  });
  const PlayerProfile = IDL.Record({
    'username' : IDL.Text,
    'bestScoresPerLevel' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat)),
    'unlockedLevels' : IDL.Vec(IDL.Nat),
  });
  const Time = IDL.Int;
  const LeaderboardEntry = IDL.Record({
    'player' : IDL.Principal,
    'score' : IDL.Nat,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteLevel' : IDL.Func([IDL.Nat], [], []),
    'getAllCommunityLevels' : IDL.Func(
        [],
        [IDL.Vec(CommunityLevel)],
        ['query'],
      ),
    'getAllLevels' : IDL.Func([], [IDL.Vec(CommunityLevel)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(PlayerProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCommunityLevel' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(CommunityLevel)],
        ['query'],
      ),
    'getLeaderboardEntries' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(LeaderboardEntry)],
        ['query'],
      ),
    'getTopRatedLevels' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(CommunityLevel)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(PlayerProfile)],
        ['query'],
      ),
    'incrementPlayCount' : IDL.Func([IDL.Nat], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'publishLevel' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'rateLevel' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([PlayerProfile], [], []),
    'submitScore' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };