/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CommunityLevel {
  'id' : bigint,
  'title' : string,
  'creator' : Principal,
  'ratings' : Array<bigint>,
  'playCount' : bigint,
  'tileData' : string,
  'averageRating' : number,
}
export interface LeaderboardEntry {
  'player' : Principal,
  'score' : bigint,
  'timestamp' : Time,
}
export interface PlayerProfile {
  'username' : string,
  'bestScoresPerLevel' : Array<[bigint, bigint]>,
  'unlockedLevels' : Array<bigint>,
}
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Only the creator (authenticated user) can delete their own level.
   */
  'deleteLevel' : ActorMethod<[bigint], undefined>,
  /**
   * / Public: anyone (including guests) can browse community levels.
   */
  'getAllCommunityLevels' : ActorMethod<[], Array<CommunityLevel>>,
  /**
   * / Public: anyone can view all levels (alias kept for frontend compatibility).
   */
  'getAllLevels' : ActorMethod<[], Array<CommunityLevel>>,
  /**
   * / Only authenticated users can read their own profile.
   */
  'getCallerUserProfile' : ActorMethod<[], [] | [PlayerProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Public: anyone can fetch a single community level.
   */
  'getCommunityLevel' : ActorMethod<[bigint], [] | [CommunityLevel]>,
  /**
   * / Public: anyone can view the leaderboard for a level.
   */
  'getLeaderboardEntries' : ActorMethod<[bigint], Array<LeaderboardEntry>>,
  /**
   * / Public: anyone can view top-rated levels.
   */
  'getTopRatedLevels' : ActorMethod<[bigint], Array<CommunityLevel>>,
  /**
   * / Public: anyone can look up a player profile (needed for leaderboard display).
   */
  'getUserProfile' : ActorMethod<[Principal], [] | [PlayerProfile]>,
  /**
   * / Only authenticated users can increment play count (guests cannot save progress).
   */
  'incrementPlayCount' : ActorMethod<[bigint], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / Only authenticated users can publish levels.
   */
  'publishLevel' : ActorMethod<[string, string], bigint>,
  /**
   * / Only authenticated users can rate a level (guests cannot submit ratings).
   */
  'rateLevel' : ActorMethod<[bigint, bigint], undefined>,
  /**
   * / Only authenticated users can save their own profile.
   */
  'saveCallerUserProfile' : ActorMethod<[PlayerProfile], undefined>,
  /**
   * / Only authenticated users can submit a score to the leaderboard.
   */
  'submitScore' : ActorMethod<[bigint, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];